---
- name: server-temp-check
  hosts: dejn-server-temp
  gather_facts: no
  become: yes
  tasks:
  - name: server ipmi temp
    shell: |
      ipmitool sdr type temp | grep "Inlet Temp" |awk '{print $1 $2,$10}'
      sleep 5
    register: output1
  - debug:
      var: output1
...
